name       : mate-settings-daemon
version    : 1.18.2
release    : 13
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-settings-daemon-1.18.2.tar.xz : 4481ac7f266f97a8e38ed057abf4790379ae66d5bedb9ee956006357dd6f536c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(fontconfig)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libxklavier)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %reconfigure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
