name       : mate-settings-daemon
version    : 1.24.0
release    : 27
source     :
    - https://github.com/mate-desktop/mate-settings-daemon/archive/v1.24.0.tar.gz : bf86e4c2dc2d1bbcb06d2f803265bd4618705d924a7ad1ed3d52c36369f58b55
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
    - mate-common
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %autogen --disable-static --enable-pulse
build      : |
    %make
install    : |
    %make_install
