name       : mate-settings-daemon
version    : 1.14.1
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-settings-daemon-1.14.1.tar.xz : 81bc955ecebd054939cb5f90338ed86616f5aebedd8ecc581600120f5db374ad
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(fontconfig)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libpulse)
    - pkgconfig(libxklavier)
    - pkgconfig(mate-desktop-2.0)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
