name       : mate-settings-daemon
version    : 1.22.0
release    : 23
source     :
    - https://github.com/mate-desktop//mate-settings-daemon/archive/v1.22.0.tar.gz : 5ccc67cb74d9a5ec7af24cdbddb3ab1e6caf68b210d49883e06be5cea4c0dc77
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
    - mate-common
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %autogen --disable-static --enable-pulse
build      : |
    %make
install    : |
    %make_install
