name       : mate-settings-daemon
version    : 1.20.1
release    : 18
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-settings-daemon-1.20.1.tar.xz : 389e829c4bdc7ad9170a4ca9a6d68c90820d17d6b58a1618cd3bfb941d2eacc2
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(fontconfig)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libxklavier)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
