name       : mate-settings-daemon
version    : 1.16.0
release    : 5
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-settings-daemon-1.16.0.tar.xz : 7876b7377adb89a11812c1b3fd44e1e78f371f8418f4f05bf5be25ea8efce4d0
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(fontconfig)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libpulse)
    - pkgconfig(libxklavier)
    - pkgconfig(mate-desktop-2.0)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
