name       : mate-settings-daemon
version    : 1.24.2
release    : 31
source     :
    - https://github.com/mate-desktop/mate-settings-daemon/releases/download/v1.24.2/mate-settings-daemon-1.24.2.tar.xz : 8c25b4f8aba69b9a0597e8759f9ef23f12ac0d3153f3f5b5a6d4afd0733f3914
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %reconfigure --disable-static --enable-pulse
build      : |
    %make
install    : |
    %make_install
