name       : mate-settings-daemon
version    : 1.20.0
release    : 16
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-settings-daemon-1.20.0.tar.xz : c5e9918ce1623953f7cf807c659406b401316b4fa7f8366bd692c9f9b4c88e5c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(fontconfig)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libxklavier)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %apply_patches
    %reconfigure
build      : |
    %make
install    : |
    %make_install
