name       : mate-settings-daemon
version    : 1.22.1
release    : 25
source     :
    - https://github.com/mate-desktop/mate-settings-daemon/archive/v1.22.1.tar.gz : e5dd85b2e9e33f9fe9acc9221de7953d2abd5fc515b384cf99aa989b3750a768
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
    - mate-common
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %autogen --disable-static --enable-pulse
build      : |
    %make
install    : |
    %make_install
