name       : mate-settings-daemon
version    : 1.27.0
release    : 35
source     :
    - https://github.com/mate-desktop/mate-settings-daemon/releases/download/v1.27.0/mate-settings-daemon-1.27.0.tar.xz : 39f8f2f3ab78675e845a3b1a2205ca85e2c9855c72a6846b17ecad23b5ffa12d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %reconfigure --disable-static --enable-pulse
build      : |
    %make
install    : |
    %make_install
