name       : mate-settings-daemon
version    : 1.24.1
release    : 28
source     :
    - https://github.com/mate-desktop/mate-settings-daemon/releases/download/v1.24.1/mate-settings-daemon-1.24.1.tar.xz : 4bf92e6f0ebaae1db3ace4a8d12fc5d40302abe0ab7d75b419e5961c47e63e58
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %reconfigure --disable-static --enable-pulse
build      : |
    %make
install    : |
    %make_install
