name       : mate-settings-daemon
version    : 1.20.4
release    : 21
source     :
    - https://github.com/mate-desktop/mate-settings-daemon/archive/v1.20.4.tar.gz : 25ccc0520ec0c9b99adc1bcad65c5bedc0664be5464d3e67742bb38e7108ca65
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(fontconfig)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libxklavier)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
    - mate-common
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %autogen --disable-static --enable-pulse
build      : |
    %make
install    : |
    %make_install
